version: "3"
services:
  api:
    image: suman1415/fastapi-suman
    depends_on:
      - postgres
    ports:
      - "80:8000"
    # volumes:
    #   - ./:/usr/src/app:ro
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY = ${SECRET_KEY}
      - ENCRYPTION_ALGORITHM = ${ENCRYPTION_ALGORITHM}
      - TOKEN_EXPIRATION_MINUTES = ${TOKEN_EXPIRATION_MINUTES}

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
